### ISSUE TITLE
API key in your source lol

### ISSUE THREAD

**Issue by strazto** [maxm33/pokedle#2]
https://github.com/maxm33/pokedle/blob/da56b6a9b5f3e1cff3a36270cf5bb18038bf2e65/app.js#L11

Dont do this

**Comment by maxm33** [comment]
It does not represent a security issue, as that api key is essential to identify the firebase app, but its access is restricted to pokedle.onrender.com only. If you have documentation that states otherwise, I'd be interested to read it. Thanks for your feedback anyways ! 😄
